"""create flags table

Revision ID: 1d3e69615ad2
Revises: 
Create Date: 2025-10-28 19:04:59.133109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3e69615ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flagString', sa.String(length=255), nullable=False),
    sa.Column('assignedTeam', sa.String(length=100), nullable=True),
    sa.Column('containerId', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_flagString'), 'flags', ['flagString'], unique=True)
    op.create_index(op.f('ix_flags_id'), 'flags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_flagString'), table_name='flags')
    op.drop_table('flags')
    # ### end Alembic commands ###
