"""create containers table

Revision ID: c2d5a20e97d0
Revises: 
Create Date: 2025-10-30 14:20:09.768677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d5a20e97d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'RUNNING', 'STOPPED', 'FAILED', 'REMOVED', name='containerstatus'), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('port', sa.String(length=20), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_container_name'), 'containers', ['container_name'], unique=True)
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_container_name'), table_name='containers')
    op.drop_table('containers')
    # ### end Alembic commands ###
